### PR TITLE
Docs: Align images

### PR DESCRIPTION
**Pull request by codeallthethingz**
My markdown previewer lied to me about how the images would display.  This forces the images onto a new line.

From this:

image

to this:

image

### CODE REVIEW

**Review by vkakerbeck — APPROVED** [review]
nice :) Can we also make them centered like it was in your preview?

**Comment by codeallthethingz** [comment]
> nice :) Can we also make them centered like it was in your preview?

Oh yes.  I'll have to convert them to image tags.  That happens automatically for our docs but not for the readme.md in the root.

**Review by vkakerbeck — APPROVED** [review]
nice, thanks!

**Comment by codeallthethingz** [comment]
> nice :) Can we also make them centered like it was in your preview?

We cannot.  If we put HTML around the images to center them, we'd have to put absolute URLs in for the images, if we do that, the PR view of the page will no longer render the images.  As far as I know there is no good way to deal with this in Github.  But I could be wrong.

**Comment by vkakerbeck** [comment]
Okay, no big deal, was just wondering

**Pull request merged**
