### PR TITLE
Fix links for slugs

### PR DESCRIPTION
**Pull request by nielsleadholm**
Changes to fix broken URLs for some of the files. Hopefully I've understood the requirement to get these links to match, i.e. I've changed the file names to match the "Title" area on the .md files. 

The only instance where I changed the *title* instead of the file name was "Outline Routing Protocol Attention", as it looks like they already matched, but my guess is that it wasn't working because of the included `/` in the title, which I don't want to add to the file! 

Is there a way to test this before merging?

### CODE REVIEW

**Comment by codeallthethingz** [comment]
Preview: https://thousandbrainsproject.readme.io/v0.0-fix-links-for-slugs/

**Comment by nielsleadholm** [comment]
Great thanks! Ironically when I go to the preview, I get a bunch of 404 Not Found even on the home page?

**Review by codeallthethingz — CHANGES_REQUESTED** [review]
Non-existent link in learning-module-improvements.md
```
We have a guide on [customizing learning modules](learning-module-improvements/contributing-learning-modules) here.
```

**Comment by codeallthethingz** [comment]
> Great thanks! Ironically when I go to the preview, I get a bunch of 404 Not Found even on the home page?

You'll have to sign in as an admin to see the preview as they're hidden from public view (an unchangeable default of readme.com)

**Review by codeallthethingz — APPROVED** [review]
LGTM

**Pull request merged**
