### PR TITLE
docs: avoid PRs based on unmerged PRs

### PR DESCRIPTION
**Pull request by tristanls**
This Pull Request proposes to formalize that Pull Requests that depend on unmerged Pull Requests are invalid and should be avoided.

The main rationale is provided in the note:
> [!NOTE]
> Pull Requests that depend on unmerged Pull Requests add unnecessary complexity to the review process: **Maintainers** must track the status of multiple Pull Requests and re-review them if the dependent Pull Request is updated. Such dependency is much easier for the Pull Request author to track and to submit the Pull Request after all dependent code is already merged to `main`.

As this is a policy-related Pull Request, I am asking all Maintainers to review it.

### CODE REVIEW

**Review by vkakerbeck — APPROVED** [review]
I support this proposal. It's a bit of a pain to review PRs that depend on other PRs or even contain code from other PRs. Just one open question to clarify: Are draft PRs okay? It seems like those serve a bit more of an informative function and don't directly request people to review so, from my side, those would have much looser requirements.

**Review by medincle — APPROVED** [review]
(removed)

**Comment by nielsleadholm** [comment]
(Sorry for the above phantom review from another Github account I have... Will be more careful about making sure I'm logged in correctly)

I like this suggestion and think it will be useful. I also like Viviane's suggestion that it could be useful to enable draft PRs to depend on unmerged PRs. This enables more visibility of in progress code where relevant, without re-introducing the burden that your suggestion is fixing, which is the requirement to review a complex, multi-dependency PR.

**Review by nielsleadholm — APPROVED** [review]

**Comment by tristanls** [comment]
Draft PRs are available in the repository, so they should be available for the use cases in y'all's comments.

I added:

> A Draft Pull Request is ignored and not triaged.

to the Pull Request Triage section.

**Review by codeallthethingz — APPROVED** [review]
LGTM

**Review by scottcanoe — APPROVED** [review]
Makes sense, LGTM.

**Pull request merged**
