### PR TITLE
Updated the vision page with responsive banner

### PR DESCRIPTION
**Pull request by dmsstern**
Responsive banner added to vision page but couldn't open a preview using Markdown Preview Enhanced ... (shrug).

### CODE REVIEW

**Comment by codeallthethingz** [comment]
Hi @dmsstern thanks for adding this and for your first ever PR! :) It's great and I'm looking forward to the other images!

A few notes: 

- We do not need all the versions of the images for responsive design, readme.com will take care of that (somewhat, and in the future the sync-tool can take care of multiple resolution images for us).  If you just put in the hd version (no more than 3000px) when it gets uploaded everything should look ok.  This also means you can use the standard markdown image reference format `!()[]` rather than a `<picture>` block.
- Images should live in the folder with the same name as the parent folder of the doc. So in this case as you're changing `docs/overview/vision-of-the-thousand-brains-project.md`
You should put the images in `docs/figures/overview/`
- Images names should be snake_case and descriptive.  For example: `../figures/vision/F01_MS_BrainLaunch_MO_Opt.png` -> `../figures/vision/brain_balloons.png`

**Comment by tristanls** [comment]
Thank you for your contribution @dmsstern!

It appears that you haven't signed our Contributor License Agreement yet.

**Please [visit this link and sign](https://na4.documents.adobe.com/public/esignWidget?wid=CBFCIBAA3AAABLblqZhA-C5ccSQcDGY-PiamH4HnZdj5p2I1oDc8FiBJ_23pReFeauFhfcIkC1XfzxC2qnBQ*).**

> [!NOTE]
> New signatures are processed during the work week. It may take some time before your signature is processed.
>
> You will be invited to the Numenta `nupic-contrib` team once your signature is processed.

**Comment by dmsstern** [comment]
Hi Tristan - Thanks for your review. I'll sign the CLA. 

Did the pull fail because of the added folder? Bad code? Or just because it was awaiting approval? You can maybe tell my strengths are not in using this setup. I'm happy to learn but I expect to need help getting up to speed.

I understand your instructions about the responsive design. The challenge - at least for the vision page banners is making them effective and accessible - as is. I don't want to encourage readers to open them. They're not 'technical diagrams' - not meant to 'explain'. They're there to break up the 'wall of text', add interest and build engagement. The versions for laptop and mobile are smaller AND different images. I was hoping to test them in previews but I can't get one in VBC (with Markdown Preview Enhanced installed). I'd also like to try a different image for the dark theme on README - if that's OK (?)

I sent all of this to Will by email. Apologies for the 'cross-post' (see comment above about being a GitNewb). Appreciate your patience, advice or instructions.

**Comment by tristanls** [comment]
Hi @dmsstern, here's a summary of what happened with the pull request status.

The CLA / verify-cla workflow check failed because you didn't sign the CLA when the check ran. The other checks haven't run yet because one of the Maintainers needs to approve them to run (I usually wait until after the CLA is processed to click the "Approve and run" button).

Screenshot 2024-11-29 at 11 40 31

**Pull request closed without merging**
